[build]
  publish = "build/web"
  command = """
    export FLUTTER_VERSION=stable &&
    git clone https://github.com/flutter/flutter.git --depth 1 --branch $FLUTTER_VERSION /opt/build/flutter &&
    export PATH="/opt/build/flutter/bin/:$PATH" &&
    flutter config --no-analytics &&
    flutter pub get &&
    flutter build web
  """
