[build]
  command = "if [ -z \"$FLUTTER_VERSION\" ]; then echo 'FLUTTER_VERSION is not set'; exit 1; fi && git clone https://github.com/flutter/flutter.git --depth 1 --branch $FLUTTER_VERSION /opt/build/flutter && export PATH=\"/opt/build/flutter/bin/:$PATH\" && flutter config --no-analytics && flutter pub get && flutter build web"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.0" # Aap yahan apna Flutter version daal sakte hain
