[build]
  # Yeh command Netlify ko batati hai ki pehle Flutter install karo, fir build karo.
  command = "git clone https://github.com/flutter/flutter.git --depth 1 --branch stable flutter && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter pub get && flutter build web --release"
  # Yeh batata hai ki final website 'build/web' folder ke andar hai.
  publish = "build/web"
