[build]
  publish = "build/web"
  command = """
    git clone https://github.com/flutter/flutter.git --depth 1 --branch stable flutter &&
    export PATH="$PATH:`pwd`/flutter/bin" &&
    flutter config --no-analytics &&
    flutter doctor -v &&
    flutter pub get &&
    flutter build web --release
  """
