name: shopedits
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# Build errors se bachne ke liye yeh section zaroori hai
dependency_overrides:
  vector_math: ^2.1.4

flutter:
  uses-material-design: true

  # Images add karne ke liye yeh section zaroori hai
  assets:
    - assets/images/
